env:
  TERM: xterm-256color

import:
  - ~/.config/alacritty/tokyonight/tokyonight_night.yml

font:
  normal:
    family: DejaVuSansM Nerd Font Mono
    style: Regular

  bold:
    family: DejaVuSansM Nerd Font Mono
    style: Bold

  oblique:
    family: DejaVuSansM Nerd Font Mono
    style: Oblique

  bold_oblique:
    family: DejaVuSansM Nerd Font Mono
    style: Bold Oblique

  size: 15

window:
  startup_mode: Fullscreen
